/*
SELECT S."IDSAU", SUM(R."IDCAR")
FROM "SAUNIER" AS S, "CARREAU" AS C, "RECOLTE" AS R
WHERE R."DATEREC" BETWEEN TO_DATE('01/01/2014', 'DD/MM/YYYY') AND TO_DATE('31/12/2014', 'DD/MM/YYYY')
AND R."IDSAU" = S."IDSAU"
GROUP BY S."IDSAU"
*/

SELECT DISTINCT S."IDSAU", R."IDCAR"
FROM "SAUNIER" AS S, "CARREAU" AS C, "RECOLTE" AS R
WHERE R."DATEREC" BETWEEN TO_DATE('01/01/2014', 'DD/MM/YYYY') AND TO_DATE('31/12/2014', 'DD/MM/YYYY')
AND R."IDSAU" = S."IDSAU"