SELECT DISTINCT S."IDSAU", S."NOMSAU", S."PRENOMSAU", R."IDREC", M."IDMAR", M."NOMMAR", M."ADRMAR"
FROM "RECOLTE" AS R, "CARREAU" AS C, "PROPRIETE" AS P, "SAUNIER" AS S, "MARAIS" AS M
WHERE S."IDSAU" IN (SELECT R."IDSAU"
					FROM "SAUNIER" AS S, "RECOLTE" AS R, "PROPRIETE" AS P, "CARREAU" AS C
					WHERE R."IDCAR" = C."IDCAR" 
					AND C."IDMAR" = P."IDMAR"
					AND P."IDPRO" = 0
				   )
AND S."IDSAU" = R."IDSAU"
AND R."IDCAR" = C."IDCAR"
AND C."IDMAR" = M."IDMAR";