SELECT S."IDSAU", S."NOMSAU", S."PRENOMSAU"
FROM "RECOLTE" AS R, "SAUNIER" AS S
WHERE R."DATEREC" BETWEEN TO_DATE('01/07/2014', 'DD/MM/YYYY') AND TO_DATE('31/07/2014', 'DD/MM/YYYY')
AND R."TYPESEL" = 'gros'
AND R."IDSAU" = S."IDSAU"
GROUP BY S."IDSAU"
ORDER BY SUM(R."QTESEL") DESC
LIMIT 1;