SELECT M."IDMAR", M."NOMMAR", M."ADRMAR"
FROM "MARAIS" AS M, "PROPRIETE" AS P
WHERE M."IDMAR" = P."IDMAR"
AND P."IDPRO" = 0
INTERSECT
SELECT M."IDMAR", M."NOMMAR", M."ADRMAR"
FROM "MARAIS" AS M, "PROPRIETE" AS P
WHERE M."IDMAR" = P."IDMAR"
AND P."IDPRO" = 1;