INSERT INTO PROPRIETAIRE (IDPRO, NOMPRO, PRENOMPRO)
VALUES (0, 'Position', 'Paul');

INSERT INTO MARAIS (IDMAR, NOMMAR, ADRMAR)
VALUES (0, 'Poitevin', '5 rue du maréchal pétin');

INSERT INTO CARREAU (IDCAR, NOMCAR, NUMEMP)
VALUES (0, 'Darbalete', 0);

INSERT INTO PROPRIETE (IDPRO, IDMAR)
VALUES (0, 0);

INSERT INTO SAUNIER (IDSAU, NOMSAU, PRENOMSAU)
VALUES (0, 'De Compostelle', 'Jacques');

INSERT INTO RECOLTE (IDREC, IDCAR, IDSAU, DATEREC, TYPESEL, QTESEL)
VALUES (0, 0, 0, TO_DATE('18/09/2021', 'DD/MM/YYYY'), 'gros', 1.748);