SELECT C."IDCAR", R."DATEREC", R."QTESEL", M."IDMAR", C."NUMEMP"
FROM "CARREAU" AS C, "RECOLTE" AS R, "MARAIS" AS M
WHERE R."TYPESEL" = 'fleur'
AND R."QTESEL" >= 0.500
AND R."IDCAR" = C."IDCAR"
AND C."IDMAR" = M."IDMAR";